services:
  tableau-elec:
    build:
      dockerfile: Dockerfile
      args:
        TZ: "Europe/Paris"
        NODE_VERSION: 20
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    tty: true
    ports:
      - '80:8080'
    networks:
      - tableau-elec-net
    command: npm run dev

networks:
  tableau-elec-net:
    driver: bridge
